language: elixir
cache: apt
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE mailgun_logger_ci_test;'
matrix:
  include:
    - elixir: 1.10
      otp_release: 23.0
notifications:
  recipients:
    - randy@jackjoe.be
