language: elixir
cache: apt
services:
  - postgresql
addons:
  postgresql:
    - "9.4"
    - "9.6"
    - "10"
    - "11"
    - "12"
before_script:
  - psql -c 'CREATE DATABASE mailgun_logger_ci_test;' -U postgres
  - psql -c "CREATE USER mailgun_logger_ci WITH PASSWORD 'johndoe';" -U postgres
  - psql -c "ALTER ROLE mailgun_logger_ci WITH CREATEDB;" -U postgres
matrix:
  include:
    - elixir: 1.9
      otp_release: 21.3
    - elixir: 1.10
      otp_release: 22.0
notifications:
  recipients:
    - randy@jackjoe.be
